#!/usr/bin/env python
import sys
import os
import subprocess
from shellpython.preprocessor import preprocess_file


def main():
    filename = sys.argv[1]
    processed_file = preprocess_file(filename, is_root_script=True)
    subprocess.call(processed_file, shell=True)


if __name__ == '__main__':
    main()
