name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9, pypy-2.7, pypy-3.6]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install mock
          python ./setup.py install
      - name: Test with pytest
        run: |
          python -m unittest discover

      - name: Run test scripts
        run: |
          example/import_from_python/import.py

      - name: Run test scripts python2
        if: matrix.python-version == '2.7' || matrix.python-version == 'pypy-2.7'
        run: |
          shellpy example/allinone/test.spy

      - name: Run test scripts python3
        if: matrix.python-version != '2.7' && matrix.python-version != 'pypy-2.7'
        run: |
          shellpy3 example/allinone/test3.spy
